### ISSUE TITLE
Unable to install  under CentOS 7.2

### ISSUE THREAD

**Issue by vfbsilva** [stepansib/ldap#1]
When I try to install the package under centos 7.2 it fails with the following error:
`composer require stepansib/ldap
PHP Warning:  Module 'ldap' already loaded in Unknown on line 0
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Using version ^2.2 for stepansib/ldap
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - oro/platform 1.9.0 requires knplabs/knp-menu 2.0.0-alpha2 -> satisfiable by knplabs/knp-menu[v2.0.0-alpha2].
    - oro/platform 1.9.0 requires knplabs/knp-menu 2.0.0-alpha2 -> satisfiable by knplabs/knp-menu[v2.0.0-alpha2].
    - oro/platform 1.9.0 requires knplabs/knp-menu 2.0.0-alpha2 -> satisfiable by knplabs/knp-menu[v2.0.0-alpha2].
    - Removal request for knplabs/knp-menu == 2.0.0.0-alpha2
    - Installation request for oro/platform (locked at 1.9.0) -> satisfiable by oro/platform[1.9.0].

Installation failed, reverting ./composer.json to its original content.
[root@blah]# composer require knplabs/knp-menu
PHP Warning:  Module 'ldap' already loaded in Unknown on line 0
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Using version ^2.1 for knplabs/knp-menu
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - oro/platform 1.9.0 requires knplabs/knp-menu 2.0.0-alpha2 -> satisfiable by knplabs/knp-menu[v2.0.0-alpha2] but these conflict with your requirements or minimum-stability.
    - oro/platform 1.9.0 requires knplabs/knp-menu 2.0.0-alpha2 -> satisfiable by knplabs/knp-menu[v2.0.0-alpha2] but these conflict with your requirements or minimum-stability.
    - oro/platform 1.9.0 requires knplabs/knp-menu 2.0.0-alpha2 -> satisfiable by knplabs/knp-menu[v2.0.0-alpha2] but these conflict with your requirements or minimum-stability.
    - Installation request for oro/platform (locked at 1.9.0) -> satisfiable by oro/platform[1.9.0].`

**Comment by stepansib** [comment]
@vfbsilva sorry for delay with answer(
Looks like the problem is not in my package. Try to create an empty directory and try to install via: `composer require stepansib/ldap`
For the clearance - i never tried to run this on CentOS. Only on Ubuntu 12-16. But i think this is not the problem.

Did you installed all Oro Platform dependencies before requiring my package?
Btw, the Oro 1.9 version caused me a lot of problems during installation. There was a many packages compatibility errors until i totally removed composer.lock and ran install comand

**Comment by stepansib** [comment]
@vfbsilva check if you enabled LDAP extension in PHP config
I found the same issue but with another php on CentOS system: [php warning module apc already loaded in unknown on line 0](http://serverfault.com/questions/610288/php-warning-module-apc-already-loaded-in-unknown-on-line-0)

**Comment by vfbsilva** [comment]
Thanks for the tips. Did you provide me the right link? What does APC have to do with my issue? I do have ldap extension enabled in php.ini
`[ldap]
; Sets the maximum number of open links or -1 for unlimited.
ldap.max_links = -1
extension=ldap.so
`

I did run in an empty dir and it have worked:
` mkdir ldap
[root@lojacrmdes web]# cd ldap/
[root@lojacrmdes ldap]# composer require stepansib/ldap
PHP Warning:  Module 'ldap' already loaded in Unknown on line 0
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Using version ^2.2 for stepansib/ldap
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing beberlei/assert (v2.5)
    Downloading: 100%         

  - Installing symfony/options-resolver (v2.8.6)
    Downloading: 100%         

  - Installing stepansib/ldap (v2.2.2)
    Downloading: 100%         

Writing lock file
Generating autoload files
[root@lojacrmdes ldap]# ls
composer.json  composer.lock  vendor
[root@lojacrmdes ldap]# cd vendor/
[root@lojacrmdes vendor]# ls
autoload.php  beberlei  composer  stepansib  symfony
[root@lojacrmdes vendor]# ls
autoload.php  beberlei  composer  stepansib  symfony
`
Where do I need to place those files? Again thanks for the swift reply.

**Comment by stepansib** [comment]
@vfbsilva you should not move this directories to you project manually because instead of installing this dependencies composer also generate autoloader. If you copy these files manually - it will not work.
So i advice you to solve composer conflicts in you project and then add my package using reguar `require` comand.
